"""SheerID 表单选择器配置（纯数据）。

说明：
- 本模块只保留静态配置（CSS selector 字典）。
- 任何等待/点击/勾选/兜底逻辑统一放到 FormFiller（Playwright Async API）中实现。
"""

from __future__ import annotations

# 仅保留选择器数据
FORM_SELECTORS = {
    "first_name": [
        "#sid-first-name",
        "input[name=\"sid-first-name\"]",
        "input[id*=\"sid-first\" i]",
        "input[name=\"firstName\"]",
        "input[autocomplete=\"given-name\"]",
        "input[id*=\"first\" i]",
    ],
    "last_name": [
        "#sid-last-name",
        "input[name=\"sid-last-name\"]",
        "input[id*=\"sid-last\" i]",
        "input[name=\"lastName\"]",
        "input[autocomplete=\"family-name\"]",
        "input[id*=\"last\" i]",
    ],
    "email": [
        "#sid-email",
        "input[name=\"sid-email\"]",
        "input[type=\"email\"]",
        "input[autocomplete=\"email\"]",
        "input[name=\"email\"]",
    ],
    "birth_date_input": [
        "input[name=\"birthDate\"]",
        "input[name*=\"birth\" i]",
        "input[name*=\"dob\" i]",
        "input[id*=\"birth\" i]",
        "input[id*=\"dob\" i]",
        "input[autocomplete=\"bday\"]",
        "input[aria-label*=\"birth\" i]",
        "input[placeholder*=\"birth\" i]",
        "input[type=\"date\"]",
    ],
    "birth_date_inputs": [
        "input[name=\"birthDate\"]",
        "input[name*=\"birth\" i]",
        "input[name*=\"dob\" i]",
        "input[id*=\"birth\" i]",
        "input[id*=\"dob\" i]",
        "input[autocomplete=\"bday\"]",
        "input[aria-label*=\"birth\" i]",
        "input[placeholder*=\"birth\" i]",
        "input[type=\"date\"]",
    ],
    "birth_month_select": [
        "select[name*=\"month\" i]",
        "select[id*=\"month\" i]",
        "select[aria-label*=\"month\" i]",
    ],
    "birth_day_select": [
        "select[name*=\"day\" i]",
        "select[id*=\"day\" i]",
        "select[aria-label*=\"day\" i]",
    ],
    "birth_year_select": [
        "select[name*=\"year\" i]",
        "select[id*=\"year\" i]",
        "select[aria-label*=\"year\" i]",
    ],
    "birth_month_combobox": [
        "#sid-birthdate__month",
        "input[name=\"sid-birthdate-month\"]",
        "#sid-birthdate_month",
        "input[id*=\"birthdate\" i][id*=\"month\" i]",
        "input[name*=\"birthdate\" i][name*=\"month\" i]",
        "input[aria-label*=\"month\" i][role=\"combobox\"]",
        "input[aria-label*=\"mes\" i]",
    ],
    "birth_day_input": [
        "#sid-birthdate-day",
        "input[name=\"sid-birthdate-day\"]",
        "#sid-birthdate_day",
        "input[id*=\"birthdate\" i][id*=\"day\" i]",
        "input[name*=\"birthdate\" i][name*=\"day\" i]",
        "input[aria-label*=\"day\" i]",
        "input[aria-label*=\"dia\" i]",
    ],
    "birth_year_input": [
        "#sid-birthdate-year",
        "input[name=\"sid-birthdate-year\"]",
        "#sid-birthdate_year",
        "input[id*=\"birthdate\" i][id*=\"year\" i]",
        "input[name*=\"birthdate\" i][name*=\"year\" i]",
        "input[aria-label*=\"year\" i]",
        "input[aria-label*=\"ano\" i]",
    ],
    "organization": [
        "input[name=\"organization.name\"]",
        "#sid-college-name",
        "input#sid-college-name",
        "input[id*=\"college\" i][role=\"combobox\"]",
        "input[role=\"combobox\"][aria-controls*=\"college\" i]",
        "input[data-qa*=\"school\" i]",
        "input[data-qa*=\"org\" i]",
        "input[data-testid*=\"school\" i]",
        "input[data-testid*=\"org\" i]",
        "input[autocomplete=\"organization\"]",
        "input[aria-label*=\"school\" i]",
        "input[placeholder*=\"school\" i]",
        "input[aria-label*=\"organization\" i]",
        "input[placeholder*=\"organization\" i]",
        "input[aria-label*=\"institution\" i]",
        "input[placeholder*=\"institution\" i]",
        "input[aria-label*=\"escuela\" i]",
        "input[placeholder*=\"escuela\" i]",
        "input[aria-label*=\"universidad\" i]",
        "input[placeholder*=\"universidad\" i]",
        "input[placeholder*=\"universidad o escuela\" i]",
        "input[aria-label*=\"organizaci\" i]",
        "input[placeholder*=\"organizaci\" i]",
        "input[aria-label*=\"instituci\" i]",
        "input[placeholder*=\"instituci\" i]",
        "input[aria-label*=\"centro\" i]",
        "input[placeholder*=\"centro\" i]",
        "input[role=\"combobox\"]",
        "[role=\"combobox\"] input",
        "input[aria-label*=\"学校\"]",
        "input[placeholder*=\"学校\"]",
        "input[aria-label*=\"大学\"]",
        "input[placeholder*=\"大学\"]",
        "input[aria-label*=\"學校\"]",
        "input[placeholder*=\"學校\"]",
        "input[aria-label*=\"大學\"]",
        "input[placeholder*=\"大學\"]",
        "input[aria-label*=\"학교\"]",
        "input[placeholder*=\"학교\"]",
        "input[aria-label*=\"대학\"]",
        "input[placeholder*=\"대학\"]",
        "input[aria-label*=\"trường\" i]",
        "input[placeholder*=\"trường\" i]",
        "input[aria-label*=\"truong\" i]",
        "input[placeholder*=\"truong\" i]",
        "input[aria-label*=\"đại học\" i]",
        "input[placeholder*=\"đại học\" i]",
        "input[aria-label*=\"dai hoc\" i]",
        "input[placeholder*=\"dai hoc\" i]",
        "input[aria-label*=\"école\" i]",
        "input[placeholder*=\"école\" i]",
        "input[aria-label*=\"etablissement\" i]",
        "input[aria-label*=\"établissement\" i]",
        "input[placeholder*=\"etablissement\" i]",
        "input[placeholder*=\"établissement\" i]",
        "input[aria-label*=\"universit\" i]",
        "input[placeholder*=\"universit\" i]",
    ],
    "submit": [
        "button[data-testid=\"submit-button\"]",
        "button[aria-label*=\"verify\" i]",
        "button:has-text(\"Verify\")",
        "button:has-text(\"Continue\")",
        "button:has-text(\"Next\")",
        "button:has-text(\"验证\")",
        "button:has-text(\"驗證\")",
        "button:has-text(\"继续\")",
        "button:has-text(\"繼續\")",
        "button:has-text(\"下一步\")",
        "button:has-text(\"확인\")",
        "button:has-text(\"인증\")",
        "button:has-text(\"계속\")",
        "button:has-text(\"다음\")",
        "button:has-text(\"Xác minh\")",
        "button:has-text(\"Xac minh\")",
        "button:has-text(\"Tiếp tục\")",
        "button:has-text(\"Tiep tuc\")",
        "button:has-text(\"Tiếp theo\")",
        "button:has-text(\"Tiep theo\")",
        "button[aria-label*=\"vérif\" i]",
        "button[aria-label*=\"verif\" i]",
        "button:has-text(\"Vérifier\")",
        "button:has-text(\"Verifier\")",
        "button:has-text(\"Continuer\")",
        "button:has-text(\"Suivant\")",
        "button:has-text(\"Suivante\")",
        "button[type=\"submit\"]",
        "input[type=\"submit\"]",
    ],
}